image: node:latest # basically tells GitLab to use Node.js docker runner to deploy the app to Now on every push. 

before_script:
  - npm i -g --unsafe-perm now # Install Now CLI on GitLab CI

cache:
  paths:
    - node_modules/ # This will tell GitLab CI to cache the dependencies

stages:
  - deploy

deploy_now:
  stage: deploy
  script: now -p -t $NOW_TOKEN
  only:
    refs:
      - master
      - pushes