image: node:latest

cache:
  paths:
    - node_modules/ # This will tell GitLab CI to cache the dependencies

before_script: 
  - npm install now --no-save # Install Now CLI on GitLab CI

stages:
  - deploy

deploy_now:
  script: now -t $NOW_TOKEN
  stage: deploy
  only:
    refs:
      - master
      - pushes
    kubernetes : active